### ISSUE TITLE
Add to My Calendars

### ISSUE THREAD

**Issue by ehn** [Miicroo/ha-swedish_calendar#11]
This is a feature request rather than an issue/bug.

Would it be possible to add the Swedish calendar data to "My Calendars" in the Home Assistant calendar view?

**Comment by Miicroo** [comment]
@ehn Yes! Sorry for the very slow response, I just found this the other day which will make it possible: https://developers.home-assistant.io/docs/core/entity/calendar/

This integration currently looks up the date every day at midnight, do you want future dates to show up in the calendar before midnight the same day? My initial thought is that it should be possible, but if you dont have that as a use case I might add that later on (and just do today).

**Comment by ehn** [comment]
It would be great to have future dates as well in the calendar but certainly not important. No need to add the feature just for my sake unless it's something you want to explore anyway. :)

**Comment by Miicroo** [comment]
Some progress on this issue, currently I have gotten one day (today) to work!

I realize that different people might use the calendar for different things, and hence there needs to be some sort of format for the calendar view. My proposition is that:
* Numbers -> Prefix with the friendly_name, e.g. `Day of week: 5` and `Week: 44`, since only `5`or `44` would be quite useless in the calendar
* Strings -> Show the value, e.g. `Sverker` for name_day
* Booleans -> If true, show the friendly_name, otherwise don't show anything. E.g. today (2022-11-04) the `day_before_work_free_holiday` will say `Day before workfree holiday` but yesterday it would have not shown at all. 
* Optional values -> If present, show the friendly_name, otherwise don't show anything. E.g. today (2022-11-04) the `eve` will say `Allhelgonaafton` but yesterday it would have not shown at all.  

For today the events (if you choose to include all of them) will look like this:
![image](https://user-images.githubusercontent.com/6637828/199957230-bae22873-261e-44e7-921e-f88ffb53627c.png)

Any feedback on this is welcome!

(In the meantime I will work on adding support for more days)

**Comment by Miicroo** [comment]
Initial testing looks good, will leave it running for a few days before merging to flush out any potential bugs or irregularities
