### ISSUE TITLE
Warning in log about

### ISSUE THREAD

**Issue by Nicxe** [Miicroo/ha-swedish_calendar#43]
This error originated from a custom integration.

Logger: custom_components.swedish_calendar.api_data
Source: custom_components/swedish_calendar/api_data.py:47
integration: Swedish calendar (documentation)
First occurred: 22:18:52 (1 occurrences)
Last logged: 22:18:52

Error when calling: https://sholiday.faboul.se/dagar/v2.1/2024/10/6, Cannot connect to host sholiday.faboul.se:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1000)')]

**Comment by Miicroo** [comment]
Thank you! I have alerted the API owner, last time he fixed it very quickly
so hoping it will soon be resolved! :)

Den sön 6 okt. 2024 22:20Niklas V ***@***.***> skrev:

**Comment by Nicxe** [comment]
Sounds good, thanks

**Comment by Miicroo** [comment]
It seems to be resolved now :)

**Comment by CrallH** [comment]
@Miicroo  it happens again:
This error originated from a custom integration.

Logger: custom_components.swedish_calendar.api_data
Source: custom_components/swedish_calendar/api_data.py:49
integration: Swedish calendar (documentation)
First occurred: 15:29:58 (5 occurrences)
Last logged: 15:30:58

Timeout when calling: https://sholiday.faboul.se/dagar/v2.1/2025/2
Timeout when calling: https://sholiday.faboul.se/dagar/v2.1/2025/3
Timeout when calling: https://sholiday.faboul.se/dagar/v2.1/2025/4

**Comment by Miicroo** [comment]
@CrallH Hmm, odd, but I suspect it depends on the API. I am currently working on a local mode, where everything is calculated rather than fetched from an online site (that I don't control). Local is the direction HomeAssistant wants to go anyways, and it seems to be the best road ahead for this component too since most holiday/calendar values never change.
The online mode will still be there (as long as the API lives on), so as soon as the local mode is done I will look into this even more

**Comment by CrallH** [comment]
Sound great, keep up the good work!
